services:
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: postgres18_db
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: kingbora
      POSTGRES_PASSWORD: 525kwb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres18_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kingbora -d myapp"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres18_data: